### ISSUE TITLE
Custom fileview to color print code

### ISSUE THREAD

**Issue by istib** [xaizek/vifm#3]
I'm trying to use the python library *pygmentize* to get a nicer file preview using the following command:

:fileview * pygmentize -O style=monokai -f console 256 -g

but the escape codes for colors aren't processed in the preview pane. any cues as to how to fix this? 

thanks

**Comment by xaizek** [comment]
> ... that's because of small amount of available color pairs. I'm going to fix that.

Finally, did it. Current implementation shouldn't imply any limitations for 16-color terminals, for 256-color terminals there is an upper bound of 256 color pairs in ncurses, but 256 should be enough for almost any use case.
